#pragma once

#include "CoreMinimal.h"

ACTION_ROGUELIKE_API DECLARE_LOG_CATEGORY_EXTERN(LogARFoundation, Log, All);
ACTION_ROGUELIKE_API DECLARE_LOG_CATEGORY_EXTERN(LogARCombat, Log, All);
ACTION_ROGUELIKE_API DECLARE_LOG_CATEGORY_EXTERN(LogARItems, Log, All);
ACTION_ROGUELIKE_API DECLARE_LOG_CATEGORY_EXTERN(LogARAction, Log, All);

